### ISSUE TITLE
Error on Loading

### ISSUE THREAD

**Issue by gil-sabado** [gflewis/sndml#1]
Even if the the first time to load, the error below is encountered.

com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'incident' already exists
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
        at com.mysql.jdbc.Util.getInstance(Util.java:384)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4232)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4164)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2615)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2776)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2832)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2781)
        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:908)
        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:788)
        at servicenow.common.datamart.DatabaseWriter.createMissingTargetTable(DatabaseWriter.java:228)
        at servicenow.common.datamart.DatabaseTableWriter.<init>(DatabaseTableWriter.java:104)
        at servicenow.common.datamart.DatabaseWriter.getTableWriter(DatabaseWriter.java:143)
        at servicenow.common.datamart.JobController.runLoad(JobController.java:241)
        at servicenow.common.datamart.JobController.runJob(JobController.java:171)
        at servicenow.common.datamart.SuiteController.runOnce(SuiteController.java:229)
        at servicenow.common.datamart.Loader.runToComplete(Loader.java:223)
        at servicenow.common.datamart.Loader.main(Loader.java:89)
Exception in thread "main" servicenow.common.datamart.SuiteInitException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'incident' already exists
        at servicenow.common.datamart.DatabaseWriter.getTableWriter(DatabaseWriter.java:146)
        at servicenow.common.datamart.JobController.runLoad(JobController.java:241)
        at servicenow.common.datamart.JobController.runJob(JobController.java:171)
        at servicenow.common.datamart.SuiteController.runOnce(SuiteController.java:229)
        at servicenow.common.datamart.Loader.runToComplete(Loader.java:223)
        at servicenow.common.datamart.Loader.main(Loader.java:89)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'incident' already exists
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:409)
        at com.mysql.jdbc.Util.getInstance(Util.java:384)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4232)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4164)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2615)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2776)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2832)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2781)
        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:908)
        at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:788)
        at servicenow.common.datamart.DatabaseWriter.createMissingTargetTable(DatabaseWriter.java:228)
        at servicenow.common.datamart.DatabaseTableWriter.<init>(DatabaseTableWriter.java:104)
        at servicenow.common.datamart.DatabaseWriter.getTableWriter(DatabaseWriter.java:143)
        ... 5 more
13:26:00 [Thread-0] INFO Datamart.ShutdownHook ShutdownHook invoked
13:26:00 [Thread-0] INFO Datamart.ShutdownHook ShutdownHook complete

**Comment by gflewis** [comment]
Hi Gil.
Can you please provide me with a copy of the configuration file that you
are using? Please XX out any passwords or IP addresses. Can you please also
let me know which JAR file you are using?  The code appears to be
attempting to create a new table named 'incident' when it generates the
error "table 'incident' already exists". This error should not occur. If
the table already exists then the loader should use the existing table, and
not create a new one. Perhaps it is getting confused if there is a table
named 'incident' in a different schema. In your case, is there any table
named 'incident' in the database?
Please reply directly to gileslewis3@gmail.com
Thanks
Giles

**Comment by gflewis** [comment]
I have reproduced this issue. It appears to be related to the behavior of the DatabaseMetaData.getTables method for MySQL. Please try the following workaround:

Specify the schema name in the `datamart.url` parameter and set the `datamart.schema` parameter to blank (or simply omit the `datamart.schema` parameter). For example

    datamart.url=jdbc:mysql://localhost/snow
    datamart.schema=
