### ISSUE TITLE
No suitable driver found

### ISSUE THREAD

**Issue by khopala** [gflewis/sndml#4]
Exception in thread "main" servicenow.common.datamart.ResourceException: java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@//<Server>:<Port>/<Instance>

Exception in thread "main" servicenow.common.datamart.ResourceException: java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@<Server>:<Port>:<Instance>

**Comment by khopala** [comment]
I am running quick start and getting above error. I tried using different format of URL but same error. 

Exception in thread "main" servicenow.common.datamart.ResourceException: java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@//:/

Exception in thread "main" servicenow.common.datamart.ResourceException: java.sql.SQLException: No suitable driver found for jdbc:oracle:thin:@::

**Comment by khopala** [comment]
I have set the below classpath and ojdbc6.jar file available in C:\sndml-2.6.5-bin\sndml-2.6.5

set classpath=.;sn-datapump-2.6.5.jar;log4j-1.2.16.jar;lib/jdom-2.0.0.jar;commons-lang3-3.1.jar;ojdbc6.jar

**Comment by khopala** [comment]
Not sure whether we need to include  Class.forName("oracle.jdbc.OracleDriver"); in ResourceManager.java file.

**Comment by gflewis** [comment]
As an experiment, can you try using sndml-2.6.5-ora.jar instead of sndml-2.6.5.jar.  The file sndml-2.6.5-ora.jar has an embedded Oracle driver. In theory, sndml-2.6.5.jar should work because you have ojdbc in your classpath. I am not sure why you are getting this error.

**Comment by khopala** [comment]
Thank your for your response. I have tried both and getting same error. Please see attached file for details.

[Error.txt](https://github.com/gflewis/sndml/files/1563732/Error.txt)

**Comment by khopala** [comment]
I have added  Class.forName("oracle.jdbc.OracleDriver") in my JDBCTest java file and it worked. Do you think that we can add the same in ResourceManager.java file.

**Comment by khopala** [comment]
C:\Raj\sndml-2.6.5-bin\sndml-2.6.5>java -version
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

**Comment by gflewis** [comment]
Thanks for brining this to my attention. I was able to reproduce your error. I think sndml-2.6.5-ora.jar might have been built with the ojdbc6 missing. I have included the latest ojdbc7 in sndml-2.6.6-ora.jar.  I have also added a new property in 2.6.6.  You can add to the properties file "datamart.driver=oracle.jdbc.OracleDriver" and it will run the requested code in ResourceManager.java. However, it should not be necessary if the jar is built correctly. Let me know if this works for you.

**Comment by khopala** [comment]
Thank you!. It has worked.  but getting below error.

12:23:46 [main] INFO Datamart.DatabaseWriter alter session set time_zone = '+0:00'
Exception in thread "main" java.lang.AssertionError: Field city has no type
        at servicenow.common.soap.FieldDefinition.<init>(FieldDefinition.java:35)
        at servicenow.common.soap.TableSchema.<init>(TableSchema.java:66)
        at servicenow.common.soap.Table.getSchema(Table.java:156)
        at servicenow.common.datamart.ResourceManager.getTableSchema(ResourceManager.java:99)
        at servicenow.common.datamart.SqlGenerator.getCreateTable(SqlGenerator.java:232)
        at servicenow.common.datamart.DatabaseWriter.createMissingTargetTable(DatabaseWriter.java:224)
        at servicenow.common.datamart.JobController.runJob(JobController.java:140)
        at servicenow.common.datamart.SuiteController.runOnce(SuiteController.java:229)
        at servicenow.common.datamart.Loader.runToComplete(Loader.java:228)
        at servicenow.common.datamart.Loader.main(Loader.java:91)

**Comment by gflewis** [comment]
This might be because your ServiceNow account lacks read permissions for one of the dictionary tables. Try the following: point to the loader to a non-production ServiceNow instance and use a ServiceNow account with admin role. Let me know if  you get the same error.

**Comment by khopala** [comment]
Thank you! your are correct. Added permission to sys_glide_object and it worked. once again thank you so much for your help and code!
